#!/bin/bash

#LOGPATH="$HOME/python/log"
LOGPATH="/home/mail2news/python/log"
M2NBIN="$HOME/python/bin/m2n.py"

# The date *yesterday*.  In other words, we want to mail a log that ran
# until midnight, after midnight.
DATE=`date --date='-1 day' +%Y-%m-%d`
FILENAME="$LOGPATH/$DATE"

cat $FILENAME | $M2NBIN \
--sender='Mixmin <mail2news@m2n.mixmin.net' \
--newsgroups='alt.privacy.anon-server.stats' \
--subject="Mixmin Mail2News log for $DATE"
